"""Shared test fixtures for BambuStudio CLI harness tests."""

import io
import json
import os
import zipfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Minimal valid 3MF model XML (one cube: 8 vertices, 12 triangles)
MINIMAL_MODEL_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter"
       xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
       xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06">
  <metadata name="Application">BambuStudio</metadata>
  <metadata name="BambuStudio:3mfVersion">1</metadata>
  <resources>
    <object id="1" name="Cube" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="20" y="0" z="0"/>
          <vertex x="20" y="20" z="0"/>
          <vertex x="0" y="20" z="0"/>
          <vertex x="0" y="0" z="20"/>
          <vertex x="20" y="0" z="20"/>
          <vertex x="20" y="20" z="20"/>
          <vertex x="0" y="20" z="20"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="2"/>
          <triangle v1="0" v2="2" v3="3"/>
          <triangle v1="4" v2="6" v3="5"/>
          <triangle v1="4" v2="7" v3="6"/>
          <triangle v1="0" v2="4" v3="5"/>
          <triangle v1="0" v2="5" v3="1"/>
          <triangle v1="1" v2="5" v3="6"/>
          <triangle v1="1" v2="6" v3="2"/>
          <triangle v1="2" v2="6" v3="7"/>
          <triangle v1="2" v2="7" v3="3"/>
          <triangle v1="3" v2="7" v3="4"/>
          <triangle v1="3" v2="4" v3="0"/>
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
  </build>
</model>
"""

MINIMAL_PRINT_CONFIG = """\
# generated by BambuStudio
layer_height = 0.2
first_layer_height = 0.2
perimeters = 2
fill_density = 15%
fill_pattern = grid
support_material = 0
"""

MINIMAL_PROJECT_CONFIG = """\
# generated by BambuStudio
printer_model = Bambu Lab A1
nozzle_diameter = 0.4
"""

MINIMAL_MODEL_CONFIG = """\
# generated by BambuStudio
"""

CONTENT_TYPES_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
  <Default Extension="png" ContentType="image/png"/>
  <Default Extension="gcode" ContentType="text/x.gcode"/>
</Types>
"""

RELS_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel-1"
    Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
"""


@pytest.fixture
def minimal_3mf(tmp_path) -> Path:
    """Create a minimal valid BBS-format 3MF file."""
    path = tmp_path / "test_cube.3mf"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", CONTENT_TYPES_XML)
        zf.writestr("_rels/.rels", RELS_XML)
        zf.writestr("3D/3dmodel.model", MINIMAL_MODEL_XML)
        zf.writestr("Metadata/print_profile.config", MINIMAL_PRINT_CONFIG)
        zf.writestr("Metadata/project_settings.config", MINIMAL_PROJECT_CONFIG)
        zf.writestr("Metadata/model_settings.config", MINIMAL_MODEL_CONFIG)
    return path


@pytest.fixture
def sample_3mf_path(minimal_3mf) -> str:
    """Return string path to the minimal 3MF fixture."""
    return str(minimal_3mf)


@pytest.fixture
def sample_result_json() -> dict:
    """Realistic result.json from a BambuStudio slice operation."""
    return {
        "return_code": 0,
        "error_string": "Success.",
        "plate_index": 0,
        "prepare_time": 1200,
        "export_time": 800,
        "sliced_plates": [
            {
                "id": 1,
                "sliced_time": 5400,
                "sliced_time_with_cache": 3200,
                "make_perimeters_time": 1800,
                "infill_time": 2100,
                "generate_support_material_time": 0,
                "triangle_count": 12,
                "warning_message": "",
                "total_predication": 1800,
                "main_predication": 1600,
                "filament_change_times": 0,
                "layer_filament_change": [],
                "obj_cached_cnt": 0,
                "objects": [
                    {
                        "id": 1,
                        "name": "Cube",
                        "triangle_count": 12,
                        "bbox": {
                            "x": 0.0,
                            "y": 0.0,
                            "z": 0.0,
                            "width": 20.0,
                            "depth": 20.0,
                            "height": 20.0,
                        },
                    }
                ],
                "filaments": [
                    {
                        "id": 0,
                        "filament_id": "GFL99",
                        "total_used_g": 5.2,
                        "main_used_g": 4.8,
                    }
                ],
            }
        ],
    }


@pytest.fixture
def mock_backend(tmp_path):
    """Create a BambuStudioBackend with mocked subprocess calls."""
    from cli_anything.bambustudio.utils.bambustudio_backend import (
        BackendResult,
        BambuStudioBackend,
    )

    backend = BambuStudioBackend.__new__(BambuStudioBackend)
    backend.binary_path = "/usr/bin/bambu-studio-mock"
    backend.debug_level = 1

    def mock_run(args, input_files=None, timeout=600):
        return BackendResult(
            returncode=0,
            stdout="Mock output",
            stderr="",
            result_json=None,
            error_message="Success",
            duration_ms=100,
            output_files=[],
        )

    backend.run = MagicMock(side_effect=mock_run)
    return backend


# Marker for tests requiring BambuStudio binary
def pytest_configure(config):
    config.addinivalue_line(
        "markers", "binary: mark test as requiring BambuStudio binary"
    )
    config.addinivalue_line(
        "markers", "studio: mark test as requiring BambuStudio GUI (skipped by default)"
    )
