"""E2E and subprocess tests for BambuStudio CLI harness.

Binary-dependent tests are marked with @pytest.mark.binary.
Subprocess tests use _resolve_cli() to find the CLI entry point.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest


# ── CLI resolver ──────────────────────────────────────────────────────────


def _resolve_cli(name: str) -> list[str]:
    """Resolve the CLI command, falling back to python -m if not installed."""
    force = os.environ.get("CLI_ANYTHING_FORCE_INSTALLED", "").strip() == "1"
    path = shutil.which(name)
    if path:
        print(f"[_resolve_cli] Using installed command: {path}")
        return [path]
    if force:
        raise RuntimeError(f"{name} not found in PATH. Install with: pip install -e .")
    module = (
        name.replace("cli-anything-", "cli_anything.")
        + "."
        + name.split("-")[-1]
        + "_cli"
    )
    print(f"[_resolve_cli] Falling back to: {sys.executable} -m {module}")
    return [sys.executable, "-m", module]


# ── Minimal 3MF XML fixtures (same as conftest but self-contained) ────────

_MINIMAL_MODEL_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter"
       xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
       xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06">
  <metadata name="Application">BambuStudio</metadata>
  <resources>
    <object id="1" name="Cube" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="20" y="0" z="0"/>
          <vertex x="20" y="20" z="0"/>
          <vertex x="0" y="20" z="0"/>
          <vertex x="0" y="0" z="20"/>
          <vertex x="20" y="0" z="20"/>
          <vertex x="20" y="20" z="20"/>
          <vertex x="0" y="20" z="20"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="2"/>
          <triangle v1="0" v2="2" v3="3"/>
          <triangle v1="4" v2="6" v3="5"/>
          <triangle v1="4" v2="7" v3="6"/>
          <triangle v1="0" v2="4" v3="5"/>
          <triangle v1="0" v2="5" v3="1"/>
          <triangle v1="1" v2="5" v3="6"/>
          <triangle v1="1" v2="6" v3="2"/>
          <triangle v1="2" v2="6" v3="7"/>
          <triangle v1="2" v2="7" v3="3"/>
          <triangle v1="3" v2="7" v3="4"/>
          <triangle v1="3" v2="4" v3="0"/>
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
  </build>
</model>
"""

_MINIMAL_PRINT_CONFIG = """\
# generated by BambuStudio
layer_height = 0.2
first_layer_height = 0.2
perimeters = 2
fill_density = 15%
"""

_MINIMAL_PROJECT_CONFIG = """\
# generated by BambuStudio
printer_model = Bambu Lab A1
nozzle_diameter = 0.4
"""

_CONTENT_TYPES_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>
"""

_RELS_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel-1"
    Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
"""


@pytest.fixture
def e2e_3mf(tmp_path) -> str:
    """Create a minimal 3MF file for subprocess tests."""
    path = tmp_path / "e2e_test.3mf"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", _CONTENT_TYPES_XML)
        zf.writestr("_rels/.rels", _RELS_XML)
        zf.writestr("3D/3dmodel.model", _MINIMAL_MODEL_XML)
        zf.writestr("Metadata/print_profile.config", _MINIMAL_PRINT_CONFIG)
        zf.writestr("Metadata/project_settings.config", _MINIMAL_PROJECT_CONFIG)
        zf.writestr("Metadata/model_settings.config", "# empty\n")
    return str(path)


# ═══════════════════════════════════════════════════════════════════════════
# E2E tests (require BambuStudio binary)
# ═══════════════════════════════════════════════════════════════════════════


@pytest.mark.binary
class TestBinaryE2E:
    """Tests that require the BambuStudio binary to be installed."""

    def test_binary_exists(self):
        """Verify BambuStudio binary is found."""
        from cli_anything.bambustudio.utils.bambustudio_backend import (
            find_bambustudio,
            BinaryNotFoundError,
        )

        try:
            path = find_bambustudio()
            assert os.path.isfile(path)
        except BinaryNotFoundError:
            pytest.skip("BambuStudio binary not installed")

    def test_binary_help(self):
        """Run --help, verify output."""
        from cli_anything.bambustudio.utils.bambustudio_backend import (
            find_bambustudio,
            BinaryNotFoundError,
        )

        try:
            binary = find_bambustudio()
        except BinaryNotFoundError:
            pytest.skip("BambuStudio binary not installed")

        result = subprocess.run(
            [binary, "--help"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        # BambuStudio CLI may return 0 or non-zero for --help
        assert len(result.stdout) > 0 or len(result.stderr) > 0


# ═══════════════════════════════════════════════════════════════════════════
# Subprocess CLI tests
# ═══════════════════════════════════════════════════════════════════════════


class TestCLISubprocess:
    """Test the CLI harness via subprocess invocation."""

    CLI_NAME = "cli-anything-bambustudio"

    @pytest.fixture(autouse=True)
    def _setup_cli(self):
        """Resolve CLI command once for the test class."""
        self.cli_cmd = _resolve_cli(self.CLI_NAME)

    def _run(self, *args: str, timeout: int = 30) -> subprocess.CompletedProcess:
        """Run the CLI with given arguments."""
        cmd = self.cli_cmd + list(args)
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

    def test_help(self):
        """--help returns exit 0."""
        result = self._run("--help")
        assert result.returncode == 0
        assert "Usage" in result.stdout or "usage" in result.stdout.lower()

    def test_json_project_info(self, e2e_3mf):
        """--json project info <3mf> returns valid JSON with ok=true."""
        result = self._run("--json", "project", "info", e2e_3mf)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        data = json.loads(result.stdout)
        assert data["ok"] is True
        assert "data" in data
        assert "path" in data["data"]

    def test_json_project_list_plates(self, e2e_3mf):
        """Returns plates array."""
        result = self._run("--json", "project", "list-plates", e2e_3mf)
        assert result.returncode == 0, f"stderr: {result.stderr}"
        data = json.loads(result.stdout)
        assert data["ok"] is True
        plates = data["data"]
        assert isinstance(plates, list)
        assert len(plates) >= 1

    def test_json_config_get(self, e2e_3mf):
        """Returns key/value."""
        result = self._run(
            "--json", "--project", e2e_3mf, "config", "get", "layer_height"
        )
        assert result.returncode == 0, f"stderr: {result.stderr}"
        data = json.loads(result.stdout)
        assert data["ok"] is True
        assert data["data"]["key"] == "layer_height"
        assert data["data"]["value"] == "0.2"

    def test_json_config_set(self, e2e_3mf, tmp_path):
        """Set value, verify changed."""
        out = str(tmp_path / "config_set_output.3mf")
        result = self._run(
            "--json",
            "--project",
            e2e_3mf,
            "config",
            "set",
            "layer_height",
            "0.16",
            "-o",
            out,
        )
        assert result.returncode == 0, f"stderr: {result.stderr}"
        data = json.loads(result.stdout)
        assert data["ok"] is True
        assert data["data"]["updated"] is True
        assert data["data"]["new_value"] == "0.16"

        # Verify by reading back
        verify = self._run("--json", "--project", out, "config", "get", "layer_height")
        assert verify.returncode == 0
        verify_data = json.loads(verify.stdout)
        assert verify_data["data"]["value"] == "0.16"
